### ISSUE TITLE
Switch to Scapy v2.4.0?

### ISSUE THREAD

**Issue by guedou** [smythtech/sdnpwn#1]
I noticed that your are using an outdate Scapy fork diverged, that does not follow evolutions and fixes from https://github.com/secdev/scapy

You should consider switching to scapy in you requirements.txt

**Comment by smythtech** [comment]
At the moment Scapy is installed using pip in the setup.sh script. The latest version available through that will be installed. Better version specification for requirements is something I might look at in the future but there hasn't been a need for it so far.

**Comment by guedou** [comment]
The scapy-Python3 package is outdated. You should use the scapy package instead.
