### ISSUE TITLE
ImportError: No module named machinery

### ISSUE THREAD

**Issue by Syrkadian** [smythtech/sdnpwn#3]
![libmachine](https://user-images.githubusercontent.com/39872088/52253915-88c53180-28bf-11e9-93ae-4782c4215da2.JPG)

**Comment by smythtech** [comment]
Hey thanks for posting issue.

The way modules are loaded was recently changed to use importlib.machinery. This should be available by default in Python3.

Can you confirm which Python version is being used to launch sdnpwn?
